### ISSUE TITLE
Warn user when experiment has a disproportionate filesize

### ISSUE THREAD

**Issue by dschreij** [open-cogsci/opensesame-extension-osweb#10]
The current implementation of osweb requires users' computers to download the entire experiment first, before it can be extracted and run. More ideal would be to stream various components in parallel of course, but that's not yet in sight.

I'm betting on users trying to run massive experiments online (because they contain many or large images or videos and such), which will take ages to download and start on participants' PCs. Maybe it is wise to let te extension issue a warning when a user tries to export an experiment that is larger that 10 MB (or any other arbitrary filesize).

**Comment by smathot** [comment]
Good idea.

**Comment by dschreij** [comment]
Alright. I will implement this then, probably this evening. Should be pretty straightforward.
