### ISSUE TITLE
Character encoding issues when converting JATOS results

### ISSUE THREAD

**Issue by smathot** [open-cogsci/opensesame-extension-osweb#17]
The first issue occurs when writing an `.xlsx` file, and should probably be fixed in smathot/python-datamatrix. The second issue seems to be a decoding issue that occurs on Python 3 on Windows.

```
Traceback (most recent call last):
  File "/Applications/OpenSesame.app/Contents/Resources/share/opensesame_extensions/oswebext/oswebext_widget.py", line 187, in _convert_results
    io.writexlsx(dm, export_path)
  File "/Applications/OpenSesame.app/Contents/Resources/lib/python3.7/site-packages/datamatrix/io/_excel.py", line 114, in writexlsx
    ws[utils.get_column_letter(colnr+1)+str(rownr+2)] = value
  File "/Applications/OpenSesame.app/Contents/Resources/lib/python3.7/site-packages/openpyxl/worksheet/worksheet.py", line 309, in __setitem__
    self[key].value = value
  File "/Applications/OpenSesame.app/Contents/Resources/lib/python3.7/site-packages/openpyxl/cell/cell.py", line 216, in value
    self._bind_value(value)
  File "/Applications/OpenSesame.app/Contents/Resources/lib/python3.7/site-packages/openpyxl/cell/cell.py", line 192, in _bind_value
    value = self.check_string(value)
  File "/Applications/OpenSesame.app/Contents/Resources/lib/python3.7/site-packages/openpyxl/cell/cell.py", line 159, in check_string
    raise IllegalCharacterError
openpyxl.utils.exceptions.IllegalCharacterError
```

And (Python 3):

```
Traceback (most recent call last):
  File "C:\Program Files (x86)\OpenSesame\share\opensesame_extensions\oswebext\oswebext_widget.py", line 174, in _convert_results
    dm = data.parse_jatos_results(jatos_results_path)
  File "C:\Program Files (x86)\OpenSesame\Lib\site-packages\osweb\data.py", line 40, in parse_jatos_results
    for line in fd:
  File "C:\Program Files (x86)\OpenSesame\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 358: character maps to <undefined>
```

**Comment by mariansauter** [comment]
Notably, this issue only occurs with Python 3.7 version (standard package), not with the 2.7 package.

**Comment by smathot** [comment]
@mariansauter Thanks. I'm pretty sure the problem lies in the fact that your operating system uses a non-utf8 file-system encoding. What version of Windows are you using exactly? But I cannot reproduce it myself.

Could you try two things to help us debug?

First, check the file-system encoding by entering the following in the debug window:

```python
import sys
sys.getfilesystemencoding()
```

What does that say?

Next, open `[OpenSesame folder]\Lib\site-packages\osweb\data.py` in a text editor, and change line 39 to:

```python
    with safe_open(jatos_path) as fd:
```

Does that fix the issue?

**Comment by mariansauter** [comment]
Thanks for getting back so quiclkly. The first code returns 'utf-8' from OS3.3.0/Py3.7 debug window.

My OS is
Windows 10 Pro
Version 1903
Build 18362.778

After changing data.py, I get a new message:

`Traceback (most recent call last):`
`  File "C:\Users\marsa\Downloads\opensesame_3.3.0-py37-win64-1\opensesame_3.3.0-py37-win64-1\share\opensesame_extensions\oswebext\oswebext_widget.py", line 187, in _convert_results`
`    io.writexlsx(dm, export_path)`
`  File "C:\Users\marsa\Downloads\opensesame_3.3.0-py37-win64-1\opensesame_3.3.0-py37-win64-1\Lib\site-packages\datamatrix\io\_excel.py", line 114, in writexlsx`
`    ws[utils.get_column_letter(colnr+1)+str(rownr+2)] = value`
`  File "C:\Users\marsa\Downloads\opensesame_3.3.0-py37-win64-1\opensesame_3.3.0-py37-win64-1\Lib\site-packages\openpyxl\worksheet\worksheet.py", line 309, in __setitem__`
`    self[key].value = value`
`  File "C:\Users\marsa\Downloads\opensesame_3.3.0-py37-win64-1\opensesame_3.3.0-py37-win64-1\Lib\site-packages\openpyxl\cell\cell.py", line 216, in value`
`    self._bind_value(value)`
`  File "C:\Users\marsa\Downloads\opensesame_3.3.0-py37-win64-1\opensesame_3.3.0-py37-win64-1\Lib\site-packages\openpyxl\cell\cell.py", line 192, in _bind_value`
`    value = self.check_string(value)`
`  File "C:\Users\marsa\Downloads\opensesame_3.3.0-py37-win64-1\opensesame_3.3.0-py37-win64-1\Lib\site-packages\openpyxl\cell\cell.py", line 159, in check_string`
`    raise IllegalCharacterError`
`openpyxl.utils.exceptions.IllegalCharacterError`

**Comment by smathot** [comment]
@mariansauter Could you send the file that triggers this issue? Because it's a bit mysterious to me. (If it contains sensitive data, you can also send it by mail or as a direct message on the forum.)

**Comment by mariansauter** [comment]
sent via email

**Comment by mariansauter** [comment]
@smathot sent via email!

**Comment by smathot** [comment]
@mariansauter Thanks! There were two separate issues, which should both be solved now. Can you check what happens if you update `python-datamatrix` and `opensesame-extension-osweb`? You can (in most environments) do that by running the following in the OpenSesame console:

```
!conda update python-datamatrix opensesame-extension-osweb -c cogsci --no-deps -y
```

**Comment by mariansauter** [comment]
Now it works! Thanks for the quick solution. 

Now I can start fully migratiing to OS 3.3.0 and Python 3.7.

**Comment by smathot** [comment]
Thanks for helping us debug!
