### ISSUE TITLE
Run experiment in browser button sometimes stay disabled

### ISSUE THREAD

**Issue by dschreij** [open-cogsci/opensesame-extension-osweb#19]
I can't really pinpoint the cause, but on some occasions the green test experiment in browser windows stays disabled after running the experiment in the browser. The only way to re-enable it, is to either restart OpenSesame, or execute one of the other (regular) run options.

**Comment by smathot** [comment]
My guess is that the issue is actually the other way around: the run-in-browser button isn't initially disabled even though it should be when you look at the compatibility check. And then later it is correctly disabled. Could you confirm that?

**Comment by dschreij** [comment]
You may be right. I think this mainly occurs with the unofficial version of 1.3.8 I am using, which has the coroutines item that isn't marked as supported yet.
