### ISSUE TITLE
"Run if" option does not accept conditional statements with a string in browser

### ISSUE THREAD

**Issue by MichlF** [open-cogsci/opensesame-extension-osweb#20]
Whether it is the "run if" in sequence items or in the repeat_cycle item, it does not accept conditional statements with a string when running in the browser.

For example:
`vars.test = "test"`  
... defined in an inline_script or a `block loop` item, will cause an experiment breaking error when put up as "Run if" statement like so `[test] == "test"` (style of writing, e.g. with/without brackets, has no influence on the issue) in one of the subsequent items in a sequence.

The error is:

> Uncaught TypeError: Cannot read property 'body' of null

When dummy coding the variable (e.g. 0 or 1) the statement runs without a problem.

I am using Open Sesame 3.3.3, Win10 and the Opensesame installation via Anaconda distribution.

**Comment by smathot** [comment]
Thanks. This is already reported at smathot/osweb#24, which is where OSWeb lives. (This repository only contains the extension that embeds it into OpenSesame.)
