### ISSUE TITLE
Allow inclusion of additional scripts

### ISSUE THREAD

**Issue by smathot** [open-cogsci/opensesame-extension-osweb#22]
@dschreij You probably have a better idea of how to implement this, but I was thinking that we could allow users to include additional `.js` files, which would then be bundled with the experiment (akin to the vendors file). This would allow users to extend the (quite) limited JavaScript functions that they have at their disposal.

**Comment by dschreij** [comment]
That is actually a really good idea, and I have been thinking of/missing this feature too at some points. We could add an element to the widget in which we allow users to specify links to the desired scripts on a CDN. Many CDNs like https://www.jsdelivr.com/ or https://cdnjs.com/ contain almost any javascript library one can think of. People can then simply specify a list of CDN links that the extension can add in the `<head>` of the generated HTML page by simply appending a `<script src="https://jsdelivr.com/link/to/some/script/js" type="text/javascript" />` for each script item. This spares us the complexity of bundling/including the script files themselves when saving an experiment for online usage.

**Comment by smathot** [comment]
So that's something we would do at the level of the `inline_javascript` items? I assumed we would need to include it in the head of the HTML page that corresponds to the experiment.

**Comment by dschreij** [comment]
We could add something like this: https://www.bogotobogo.com/Qt/Qt5_QListView_QStringListModel_ModelView_MVC.php in which people can enter custom URLs.

**Comment by dschreij** [comment]
> So that's something we would do at the level of the `inline_javascript` items? I assumed we would need to include it in the head of the HTML page that corresponds to the experiment.

No we need to do it a the extension level, where the buttons `Export to Jatos/standalone` and the compatibility check are located.

**Comment by smathot** [comment]
This has been implemented.
