### ISSUE TITLE
Submenu assignment of OSWeb extension changes after psynteract installation 

### ISSUE THREAD

**Issue by PascalKieslich** [open-cogsci/opensesame-extension-osweb#29]
Hi all,

we are currently updating the psynteract plugins and extension for OpenSesame and discovered an issue that is affecting the menu position of the OSWeb extension.

Before installing psynteract, the OSWeb extension is assigned to the Tools menu:
![grafik](https://user-images.githubusercontent.com/13104756/140196729-f360590f-1edb-422f-9701-32eb8c9bd03d.png)

After installing psynteract, the OSWeb extension is assigned to the Psynteract menu:
![grafik](https://user-images.githubusercontent.com/13104756/140196780-93115585-e910-4468-9dce-66e6e6085f42.png)

We checked everything within the psynteract extension and could not find a bug there so we were wondering whether this might be an issue on the OSWeb extension side?

If you would like to replicate the issue, feel free to install the current development version of psynteract in OpenSesame with the following command:
`!pip install https://github.com/psynteract/psynteract-os/archive/master.zip`

Thanks in advance for your help!

Best,

Pascal

**Comment by smathot** [comment]
Thanks!
