### ISSUE TITLE
How to store data in Jatos

### ISSUE THREAD

**Issue by dschreij** [open-cogsci/opensesame-extension-osweb#9]
Currently the data of a single participant in Jatos is saved as a json string, containing an array of objects, in which each object is an entry of the logger. For example:

``` jsonc
[
{acc: 0, rt: 412, ... } // sample 1
{acc: 50, rt: 822, ...} // sample 2
]
```

When the data of multiple participants is exported from Jatos, this become problematic, because the json strings of all participants are simply concatenated, and as a result do not consist of valid JSON anymore:

``` jsonc
// an open-array symbol is expected here
[ // Participant 1
{acc: 0, rt: 412, ... } // sample 1
{acc: 50, rt: 822, ...} // sample 2
] // a comma is expected here
[ // Participant 2
{acc: 0, rt: 412, ... } // sample 1
{acc: 50, rt: 822, ...} // sample 2
]
// a close array symbol is expected here
```

Ideally, the resulting export file is one single array, containing all samples of all participants:

``` jsonc
[
{subject_nr: 1, acc: 0, rt: 412, ... } // sample 1
{subject_nr: 1, acc: 50, rt: 822, ...} // sample 2
...
{subject_nr: 2, acc: 100, rt: 442, ... } // sample 1
{subject_nr: 2, acc: 50, rt: 789, ...} // sample 2
]
```
because this would make loading the data into pandas very simple:

```python
with open('data.json') as fp:
    data = pd.read_json(fp)
```

I have yet to find a way to make the latter format possible in Jatos, since one is not allowed to preprocess the data that is exported. Do you have any ideas on how to tackle this problem?

**Comment by smathot** [comment]
I noticed that too. A related problem occurs when the participant aborts the experiment halfway, in which case the data is also not valid JSON. I don't see an easy way to solve this in JATOS per se, but we could add a simple utility to the OSWeb extension that fixes these corruptions, and also allows users to convert the data into a format that they are more familiar with, such as `.csv` and `.xlsx`.

**Comment by dschreij** [comment]
Yes, that seems like a good idea for now, although I think it's worth suggesting an improvement on his process to the Jatos devs in the near future, if we have a clearer picture of the optimal way of doing this. Ideally one can download the data and import it into their analysis pipeline without having to add OpenSesame again somewhere here, in my opinion.

As for the current best way of handling this: What if we just write each single entry to the jatos log and add the symbols to form correct JSON afterwards in the OS extension. After each response, something like
```
{subject_nr: 1, acc: 0, rt: 412, ... } 
``` 
is currently already written to the jatos log, and we can leave it at that. The data stored in jatos will thus be a collection of entries such as:

```
{subject_nr: 1, acc: 0, rt: 412, ... } 
{subject_nr: 1, acc: 10, rt: 412, ... }
{subject_nr: 1, acc: 50, rt: 631, ... } 
```

The only thing we need to do then is add commas between the entries (which should be as easy as finding the newline character and prepend the comma there), and encapsulate everything in `[...]` array brackets. 
Or am I being to simplistic about this?
